"""Rule validator Tier 1 - validates generated cleaning rules via LLM.

This module validates Python code generated by rule_generator.py using
a lightweight LLM call. It does NOT generate code - only validates,
keeping token usage minimal.

Workflow:
1. Takes GeneratedRule + codebook entry + sample data
2. Sends short validation prompt to LLM (Kimi K2.5 or GLM-5, free)
3. If LLM says OK: return validated code
4. If LLM detects errors: adjust code and retry (max 2 attempts)
5. If still failing after retries: escalate to Tier 2

This is the Tier 1 validator in the 3-Tier system:
- Tier 1 (this): Pattern-based rules, validated by LLM
- Tier 2: Batch LLM generation for complex cases
- Tier 3: Individual LLM handling for edge cases
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any, Optional, Union

if TYPE_CHECKING:
    import pandas as pd
    from surveys.codebook_parser.schemas.variable_schema import VariableSchema
    from surveys.pattern_engine.rule_generator import GeneratedRule

logger = logging.getLogger(__name__)

DEFAULT_MODEL = "opencode/glm-5-free"
FALLBACK_MODEL = "opencode/glm-4.7-free"

VALIDATION_PROMPT = """Valide ce code de nettoyage pour une variable de sondage.

## Codebook
Variable: {var_name}
Label: {var_label}
Type: {var_type}

Valeurs autorisées:
{value_labels}

Codes manquants: {missing_codes}

## Code généré
```python
{generated_code}
```

## Échantillon de données (5 premières valeurs)
{sample_data}

## Ta tâche
Vérifie que le mapping est correct selon le codebook:
1. Les valeurs numériques correspondent-elles aux labels?
2. Les codes manquants sont-ils gérés (→ None/NaN)?
3. Y a-t-il des valeurs dans l'échantillon non mappées?

Réponds en JSON:
```json
{{
  "valid": true/false,
  "errors": ["erreur1", "erreur2"] ou [],
  "corrected_code": "code corrigé si erreur" ou null
}}
```"""


@dataclass
class ValidationError:
    error_type: str
    message: str
    suggested_fix: Optional[str] = None


@dataclass
class ValidationResult:
    is_valid: bool
    original_code: str
    corrected_code: Optional[str] = None
    errors: list[ValidationError] = field(default_factory=list)
    attempts: int = 1
    escalated: bool = False
    model_used: Optional[str] = None

    @property
    def final_code(self) -> str:
        return self.corrected_code if self.corrected_code else self.original_code


class RuleValidator:
    """Validate generated cleaning rules using LLM.

    Usage:
        validator = RuleValidator()
        result = validator.validate(rule, codebook_entry, sample_data)
        if result.is_valid:
            print(result.final_code)
        elif result.escalated:
            print("Needs Tier 2 processing")
        else:
            print(f"Errors: {result.errors}")
    """

    def __init__(
        self,
        model: Optional[str] = None,
        max_attempts: int = 2,
        temperature: float = 0.1,
    ):
        self.model = model or DEFAULT_MODEL
        self.max_attempts = max_attempts
        self.temperature = temperature

    def validate(
        self,
        rule: "GeneratedRule",
        codebook_entry: Optional[Union["VariableSchema", dict]] = None,
        sample_data: Optional[Union["pd.Series", list]] = None,
    ) -> ValidationResult:
        """Validate a generated rule against codebook and sample data.

        Args:
            rule: GeneratedRule from rule_generator
            codebook_entry: VariableSchema or dict with value_labels, missing_codes
            sample_data: pandas Series or list of sample values

        Returns:
            ValidationResult with validation status and corrected code if needed
        """
        current_code = rule.code
        all_errors: list[ValidationError] = []

        for attempt in range(1, self.max_attempts + 1):
            response = self._call_llm(
                rule=rule,
                codebook_entry=codebook_entry,
                sample_data=sample_data,
                current_code=current_code,
            )

            result = self._parse_response(response)

            if result.get("valid", False):
                return ValidationResult(
                    is_valid=True,
                    original_code=rule.code,
                    corrected_code=current_code if attempt > 1 else None,
                    attempts=attempt,
                    model_used=self.model,
                )

            errors = result.get("errors", [])
            for err in errors:
                all_errors.append(
                    ValidationError(error_type="validation", message=err)
                )

            corrected = result.get("corrected_code")
            if corrected and attempt < self.max_attempts:
                current_code = corrected
                logger.info(f"Attempt {attempt}: retrying with corrected code")
            elif attempt >= self.max_attempts:
                break

        return ValidationResult(
            is_valid=False,
            original_code=rule.code,
            corrected_code=None,
            errors=all_errors,
            attempts=self.max_attempts,
            escalated=True,
            model_used=self.model,
        )

    def _call_llm(
        self,
        rule: "GeneratedRule",
        codebook_entry: Optional[Union["VariableSchema", dict]],
        sample_data: Optional[Union["pd.Series", list]],
        current_code: str,
    ) -> str:
        """Call LLM with validation prompt."""
        try:
            import litellm
        except ImportError as e:
            raise ImportError("litellm is required for RuleValidator") from e

        prompt = self._build_prompt(rule, codebook_entry, sample_data, current_code)

        response = litellm.completion(
            model=self.model,
            messages=[
                {"role": "user", "content": prompt},
            ],
            response_format={"type": "json_object"},
            temperature=self.temperature,
        )

        return response.choices[0].message.content

    def _build_prompt(
        self,
        rule: "GeneratedRule",
        codebook_entry: Optional[Union["VariableSchema", dict]],
        sample_data: Optional[Union["pd.Series", list]],
        current_code: str,
    ) -> str:
        """Build the validation prompt."""
        var_name = rule.original_var
        var_label = ""
        var_type = "unknown"
        value_labels_str = ""
        missing_codes_str = "[]"
        sample_str = "Non disponible"

        if codebook_entry:
            if hasattr(codebook_entry, "var_label"):
                var_label = codebook_entry.var_label or ""
                var_type = codebook_entry.var_type or "unknown"
                missing_codes_str = str(codebook_entry.missing_codes or [])

                if codebook_entry.value_labels:
                    lines = []
                    for vl in codebook_entry.value_labels:
                        missing_mark = " (missing)" if vl.is_missing else ""
                        lines.append(f"  {vl.value}: {vl.label}{missing_mark}")
                    value_labels_str = "\n".join(lines)
            elif isinstance(codebook_entry, dict):
                var_label = codebook_entry.get("var_label", "")
                var_type = codebook_entry.get("var_type", "unknown")
                missing_codes_str = str(codebook_entry.get("missing_codes", []))

                vls = codebook_entry.get("value_labels", [])
                if vls:
                    lines = []
                    for vl in vls:
                        if isinstance(vl, dict):
                            missing_mark = " (missing)" if vl.get("is_missing") else ""
                            lines.append(f"  {vl.get('value')}: {vl.get('label')}{missing_mark}")
                    value_labels_str = "\n".join(lines)

        if sample_data is not None:
            try:
                import pandas as pd

                if isinstance(sample_data, pd.Series):
                    sample = sample_data.head(5).tolist()
                else:
                    sample = list(sample_data)[:5]
                sample_str = str(sample)
            except ImportError:
                sample_str = str(list(sample_data)[:5] if sample_data else [])

        return VALIDATION_PROMPT.format(
            var_name=var_name,
            var_label=var_label,
            var_type=var_type,
            value_labels=value_labels_str or "Aucun",
            missing_codes=missing_codes_str,
            generated_code=current_code,
            sample_data=sample_str,
        )

    def _parse_response(self, response: str) -> dict[str, Any]:
        """Parse LLM JSON response."""
        try:
            data = json.loads(response)
            return {
                "valid": data.get("valid", False),
                "errors": data.get("errors", []),
                "corrected_code": data.get("corrected_code"),
            }
        except json.JSONDecodeError:
            return {
                "valid": False,
                "errors": ["Failed to parse LLM response as JSON"],
                "corrected_code": None,
            }


def validate_rule(
    rule: "GeneratedRule",
    codebook_entry: Optional[Union["VariableSchema", dict]] = None,
    sample_data: Optional[Union["pd.Series", list]] = None,
    model: Optional[str] = None,
) -> ValidationResult:
    """Convenience function to validate a single rule.

    Args:
        rule: GeneratedRule from rule_generator
        codebook_entry: VariableSchema or dict with value_labels, missing_codes
        sample_data: pandas Series or list of sample values
        model: LLM model to use (default: opencode/glm-5-free)

    Returns:
        ValidationResult with validation status
    """
    validator = RuleValidator(model=model)
    return validator.validate(rule, codebook_entry, sample_data)
