# ses_region — Région administrative du Québec
# Source: nomx
df_clean['ses_region'] = df['nomx'].map({
    '01': 'bas_saint_laurent',
    '02': 'saguenay_lac_saint_jean',
    '03': 'quebec_rmr',
    '04': 'mauricie',
    '05': 'estrie',
    '06': 'montreal',
    '07': 'outaouais',
    '08': 'abitibi_temiscamingue',
    '09': 'cote_nord',
    '11': 'gaspesie',
    '12': 'chaudiere_appalaches_rmr',
    '13': 'laval',
    '14': 'lanaudiere_rmr',
    '15': 'laurentides_rmr',
    '16': 'monteregie_rmr',
    '17': 'centre_du_quebec',
    '24': 'lanaudiere_autres',
    '25': 'laurentides_autres',
    '26': 'monteregie_autres',
    '32': 'chaudiere_appalaches_autres',
    '33': 'quebec_autres',
})
CODEBOOK_VARIABLES['ses_region'] = {
    'original_variable': 'nomx',
    'question_label': "Régions administratives du Québec: 21 sous-groupes",
    'type': 'categorical',
    'value_labels': {
        'bas_saint_laurent': "Bas-Saint-Laurent",
        'saguenay_lac_saint_jean': "Saguenay/Lac-Saint-Jean",
        'quebec_rmr': "Québec - RMR",
        'mauricie': "Mauricie",
        'estrie': "Estrie",
        'montreal': "Montréal",
        'outaouais': "Outaouais",
        'abitibi_temiscamingue': "Abitibi/Témiscamingue",
        'cote_nord': "Côte-Nord",
        'gaspesie': "Gaspésie",
        'chaudiere_appalaches_rmr': "Chaudière-Appalaches - RMR",
        'laval': "Laval",
        'lanaudiere_rmr': "Lanaudière - RMR",
        'laurentides_rmr': "Laurentides - RMR",
        'monteregie_rmr': "Montérégie - RMR",
        'centre_du_quebec': "Centre-du-Québec",
        'lanaudiere_autres': "Lanaudière-Autres",
        'laurentides_autres': "Laurentides-Autres",
        'monteregie_autres': "Montérégie-Autres",
        'chaudiere_appalaches_autres': "Chaudières-Appalaches Autres",
        'quebec_autres': "Québec Autres",
    },
}
