# op_top_issue — Most important issue in the provincial election
# Source: q1
# Assumption: code 96 ("write-in response") treated as valid category 'other'
df_clean['op_top_issue'] = df['q1'].map({
    '01': 'health',
    '02': 'change_government',
    '03': 'change',
    '04': 'economy',
    '05': 'finances',
    '06': 'education',
    '07': 'family',
    '08': 'environment',
    '09': 'remove_charest',
    '10': 'sovereignty',
    '11': 'question_model',
    '12': 'diminish_pq',
    '13': 'tax_cuts',
    '14': 'minority_govt',
    '15': 'lesson_to_parties',
    '16': 'integrity',
    '17': 'continuity',
    '18': 'future_quebec',
    '19': 'accommodation_immigration',
    '96': 'other',
    '98': np.nan,
    '99': np.nan,
})
CODEBOOK_VARIABLES['op_top_issue'] = {
    'original_variable': 'q1',
    'question_label': "Pour vous personnellement, quel était l'enjeu le plus important de cette élection provinciale?",
    'type': 'categorical',
    'value_labels': {
        'health': "La santé / l'état du système de santé",
        'change_government': "Changer de gouvernement",
        'change': "Le changement",
        'economy': "L'économie / le développement économique",
        'finances': "Les finances publiques / la dette / la gestion des finances",
        'education': "L'éducation",
        'family': "La famille",
        'environment': "L'environnement",
        'remove_charest': "Se débarrasser de Jean Charest",
        'sovereignty': "La souveraineté / l'indépendance du Québec",
        'question_model': "Renverser / remmettre en question le modèle québécois",
        'diminish_pq': "Reléguer le PQ au rang de tiers parti",
        'tax_cuts': "Les baisses d'impôts / de taxes",
        'minority_govt': "Élire un gouvernement minoritaire",
        'lesson_to_parties': "Servir une leçon au vieux partis",
        'integrity': "La franchise / l'intégrité des partis politiques",
        'continuity': "La continuité / un gouvernement libéral majoritaire",
        'future_quebec': "L'avenir du Québec",
        'accommodation_immigration': "Accomodements raisonnables / immigration / intégration",
        'other': "Réponse écrite par le répondant",
    },
}
